GET https://api.github.com/repos/schmelto/portfolio

###

GET https://api.github.com/repos/schmelto/100-days-of-code

###

GET https://api.github.com/repos/schmelto/NewsApp

###

GET https://api.github.com/repos/schmelto/ImpactHackathon

###

GET https://api.github.com/users/schmelto
