name: Feature Request
description: Suggest a feature
title: "[Feat]: "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggest an idea for this project!
  - type: textarea
    id: feature-request
    attributes:
      label: Feature request
      description: Tell us what you want do have.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/schmelto/portfolio/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
